name: API Tests

on:
  push:
    branches: [ main, master, finalproject ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

defaults:
  run:
    working-directory: "Final Course Project"

jobs:
  api-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run API tests
      run: npm run test:api
      continue-on-error: true
    - name: Generate Allure Report
      run: npm run report:generate
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report-api
        path: Final Course Project/allure-report/
        retention-days: 30
    - name: Post Allure Report to PR
      if: github.event_name == 'pull_request'
      uses: allure-framework/allure-action@master
      with:
        report-directory: "Final Course Project/allure-report"
        github-token: ${{ secrets.GITHUB_TOKEN }}
